language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-playground npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-playground"
  env: "Dockerplayground-env"
  bucket_name: "elasticbeanstalk-us-east-2-092858577025"
  bucket_path: "docker-playground"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"